pipeline {
    agent any

    stages {

        stage ('Build Docker Image') {
            steps {
                script {
                    dockerapp = docker.build ("passarela/kube-news:${env.BUILD_ID}", '-f ./Aula2-KubeNews/src/Dockerfile ./Aula2-KubeNews/src')
                }
            }
        }

        stage ('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        dockerapp.push ("${env.BUILD_ID}")
                        dockerapp.push ('latest')
                        }
                }
            }
        }

        stage ("deploy kubernetes") {

            steps {
                withKubeconfig ([credentialsId: 'kubeconfig']) {
                        sh 'kubectl apply -f ./Aula2-KubeNews/k8s/deployment.yaml'
                }
            }

        }

    }
}